const labels = {
  Learn_CSS: 'Вивчення CSS',
  CSS_first_steps: 'Перші кроки у CSS',
  CSS_first_steps_overview: 'Перші кроки у CSS — огляд',
  What_is_CSS: 'Що таке CSS?',
  Getting_started_with_CSS: 'Початок роботи з CSS',
  How_CSS_is_structured: 'Яку структуру має CSS',
  How_CSS_works: 'Як працює CSS',
  Using_your_new_knowledge: 'Застосування щойно набутих знань',
  CSS_building_blocks: 'Конструктивні блоки CSS',
  CSS_building_blocks_overview: 'Конструктивні блоки CSS — огляд',
  Cascade_and_inheritance: 'Каскад і успадкування',
  CSS_selectors: 'Селектори CSS',
  The_box_model: 'Блокова модель',
  Backgrounds_and_borders: 'Рамки та тло',
  Handling_different_text_directions: 'Обробка різних орієнтацій тексту',
  Overflowing_content: 'Переповнення вмісту',
  Values_and_units: 'Значення та одиниці виміру',
  Sizing_items_in_CSS: 'Встановлення розмірів елементів у CSS',
  Images_media_and_form_elements: 'Зображення, медіаконтент, і елементи форм',
  Styling_tables: 'Стилізація таблиць',
  Debugging_CSS: 'Зневадження CSS',
  Organizing_your_CSS: 'Організація коду на CSS',
  Styling_text: 'Стилізація тексту',
  Styling_text_overview: 'Стилізація тексту — огляд',
  Fundamental_text_and_font_styling: 'Базова стилізація тексту та шрифта',
  Styling_lists: 'Стилізація списків',
  Styling_links: 'Стилізація посилань',
  Web_fonts: 'Web-шрифти',
  Assessment_typesetting_a_community_school_homepage:
    'Оцінювання: верстка шкільного вебсайту',
  CSS_layout: 'CSS-верстка',
  CSS_layout_overview: 'CSS-верстка — огляд',
  Layout_introduction: 'Вступ до CSS-верстки',
  Normal_Flow: 'Звичайний плин',
  Flexbox: 'Flexbox',
  Grids: 'Grid-сітки',
  Floats: 'Floats',
  Positioning: 'Позиціювання',
  'Multiple-column_Layout': 'Багато-колонкова верстка',
  Responsive_design: 'Адаптивна верстка',
  Media_queries: 'Медіазапити — настанови для початківців',
  Legacy_Layout_Methods: 'Застарілі способи верстки',
  Supporting_Older_Browsers: 'Підтримка старих браузерів',
  Fundamental_Layout_Comprehension: 'Фундаментальне розуміння розкладки',
  Color_picker_tool: 'Інструмент для обирання кольору',
  'Box-shadow_generator': 'Генератор блокової тіні',
  'Border-image_generator': 'Генератор зображення для рамки',

  // TODO better place for that?
  Animations: 'Анімації',
  'Using CSS animations': 'Застосування CSS-анімацій',
  'Backgrounds and Borders': 'Рамки та тла',
  'Using multiple backgrounds': 'Застосування множинних тл',
  'Resizing background images': 'Зміна розміру зображень на тлі',
  'Box model': 'Блокова модель',
  'Box alignment': 'Вирівнювання блока',
  Columns: 'Колонки',
  'Conditional rules': 'Правила з умовами',
  'CSSOM view': 'CSSOM-вигляд',
  Flexbox: 'Flexbox',
  'Flow layout': 'Потокова розкладка',
  Fonts: 'Шрифти',
  Grid: 'Grid-сітки',
  Images: 'Зображення',
  'Lists and counters': 'Списки та лічильники',
  'Logical properties': 'Логічні властивості',
  'Media queries': 'Медіазапити',
  'Scroll snap': 'Захоплення прокрутки',
  Shapes: 'Фігури',
  Text: 'Текст',
  Transforms: 'Трансформації',
  Transitions: 'Переходи',
  'Layout cookbook': 'Книга рецептів верстки',
  Tools: 'Інструменти',
  'Box alignment in block layout': 'Вирівнювання блока у блоковій розкладці',
  'Box alignment in flexbox': 'Вирівнювання блока на flexbox',
  'Box alignment in grid layout': 'Вирівнювання блока на grid-сітках',
  'Box alignment in multi-column layout':
    'Вирівнювання блока у багатоколонковій верстці',
  'Introduction to the CSS basic box model':
    'Вступ до основ блокової моделі CSS',
  'Mastering margin collapsing': 'Схлопування зовнішніх відступів',
  'Basic concepts of Multicol': 'Основні ідеї багатоколонкової верстки',
  'Styling columns': 'Стилізація колонок',
  'Spanning and balancing': 'Заповнення і балансування',
  'Handling overflow in Multicol':
    'Обробка переповнення у багатоколокновій верстці',
  'Content breaks in Multicol': 'Розриви вмісту у багатоколонковій верстці',
  'Using feature queries': 'Застосування запитів характеристик',
  'Coordinate systems': 'Координатні системи',
  'Basic concepts of Flexbox': 'Основні ідеї Flexbox',
  'Comparison with other layout methods':
    'Порівняння з іншими способами розкладки',
  'Aligning items in a flex container':
    'Вирівнювання елементів у flex-контейнерах',
  'Ordering flex items': 'Упорядкування flex-елементів',
  'Controlling flex item ratios': 'керування пропорціями flex-елементів',
  'Mastering wrapping of flex items': 'Перенесення рядків flex-елементів',
  'Typical use cases of Flexbox': 'Типові випадки для застосування Flexbox',
  'Backwards compatibility of Flexbox': 'Backwards compatibility of Flexbox',
  'Block and Inline layout in normal flow':
    'Лінійна і блокова розкладка в нормальному плині документу',
  'In flow and Out of flow': 'У плині та поза плином',
  'Formatting contexts explained': 'Пояснення контекстів форматування',
  'Flow layout and writing modes':
    'Потокова розкладка та режими написання тексту',
  'Flow layout and overflow': 'Потокова розкладка і переповнення',
  'OpenType font features guide':
    'Настанови щодо особливостей шрифтів OpenType',
  'Variable fonts guide': 'Настанови по варіативних шрифтах',
  'Basics concepts of grid layout': 'Основні ідеї розкладки за сіткою',
  'Relationship to other layout methods':
    "Зв'язок з іншими способами розкладки",
  'Line-based placement': 'Розміщення елементів відносно рядка',
  'Grid template areas': 'Grid template areas', // TODO: ???
  'Layout using named grid lines':
    'Розкладання елеементів за іменованими рядками',
  'Auto-placement in grid layout': 'Авторозміщення у grid-сітках',
  'Box alignment in grid layout': 'Вирівнювання блока у grid-сітках',
  'Grids, logical values and writing modes':
    'Сітки, логічні значення і режими написання',
  'Grid layout and accessibility': 'Доступність вмісту у Grid-розкладках',
  'Grid Layout and progressive enhancement':
    'Grid-сітки та прогресивне поліпшення',
  'Realizing common layouts using grids':
    'Реалізація поширених розкладок із застосуванням сіток',
  Subgrid: 'Підсітки',
  'Masonry layout': 'Розкладка замощенням',
  'Using CSS gradients': 'Застосування градієнтів у CSS',
  'Using CSS counters': 'Застосування лічильників у CSS',
  'Consistent list indentation': 'Узгоджені відступи у списках',
  'Basic concepts': 'Загальні принципи',
  'Floating and positioning': 'Позиціонування та плаваючий вміст',
  'Margins, borders and padding': 'Відступи, рамки та поля',
  Sizing: 'Розміри',
  'Using media queries': 'Застосування медіазапитів',
  'Using media queries for accessibility':
    'Застосування медіазапитів у контексті доступності',
  'Testing media queries programmatically': 'Програмне тестування медіазапитів',
  'Understanding CSS z-index': 'Розуміння z-індексу у CSS',
  'Basic concepts of scroll snap': 'Основні принципи захоплення прокрутки',
  'Browser compatibility and scroll snap':
    'Захоплення прокрутки та його сумісність із браузерами',
  'Overview of shapes': 'Фігури — огляд',
  'Shapes from box values': 'Створення фігур на базі параметрів блока',
  'Basic shapes': 'Основні фігури',
  'Shapes from images': 'Створення фігур із зображень',
  'Wrapping and breaking text': 'Преноси та розриви тексту',
  'Using transforms': 'Застосування трансформацій',
  'Using transitions': 'Застосування переходів',
  'Media objects': "Медіа-об'єкти",
  Columns: 'Колонки',
  'Center an element': 'Центрування елементу',
  'Sticky footers': 'Липкий нижній колонтитул',
  'Split navigation': 'Розділена навігація',
  'Breadcrumb navigation': 'Навігація за хлібними крихтами',
  'List group with badges': 'Список елементів із лейбами',
  Pagination: 'Розбиття на сторінки',
  Card: 'Картка',
  'Grid wrapper': 'Обгортка сітки',
};

module.exports.navLabels = labels;
module.exports.default = () => '';
