const labels = {
    'Learn_CSS': 'Learn CSS',
    'CSS_first_steps': 'CSS first steps',
    'CSS_first_steps_overview': 'CSS first steps overview',
    'What_is_CSS':  'What is CSS?',
    'Getting_started_with_CSS': 'Getting started with CSS',
    'How_CSS_is_structured': 'How CSS is structured',
    'How_CSS_works': 'How CSS works',
    'Using_your_new_knowledge': 'Using your new knowledge',
    'CSS_building_blocks': 'CSS building blocks',
    'CSS_building_blocks_overview': 'CSS building blocks overview',
    'Cascade_and_inheritance': 'Cascade and inheritance',
    'CSS_selectors': 'CSS selectors',
    'The_box_model': 'The box model',
    'Backgrounds_and_borders': 'Backgrounds and borders',
    'Handling_different_text_directions': 'Handling different text directions',
    'Overflowing_content': 'Overflowing content',
    'Values_and_units': 'Values and units',
    'Sizing_items_in_CSS': 'Sizing items in CSS',
    'Images_media_and_form_elements': 'Images, media, and form elements',
    'Styling_tables': 'Styling tables',
    'Debugging_CSS': 'Debugging CSS',
    'Organizing_your_CSS': 'Organizing your CSS',
    'Styling_text': 'Styling text',
    'Styling_text_overview': 'Styling text overview',
    'Fundamental_text_and_font_styling': 'Fundamental text and font styling',
    'Styling_lists': 'Styling lists',
    'Styling_links': 'Styling links',
    'Web_fonts': 'Web fonts',
    'Assessment_typesetting_a_community_school_homepage': 'Assessment: Typesetting a community school homepage',
    'CSS_layout': 'CSS layout',
    'CSS_layout_overview': 'CSS layout overview',
    'Layout_introduction' : 'Introduction to CSS layout',
    'Normal_Flow' : 'Normal Flow',
    'Flexbox': 'Flexbox',
    'Grids' : 'Grids',
    'Floats': 'Floats',
    'Positioning': 'Positioning',
    'Multiple-column_Layout': 'Multiple-column Layout',
    'Responsive_design': 'Responsive design',
    'Media_queries': 'Beginner\'s guide to media queries',
    'Legacy_Layout_Methods': 'Legacy Layout Methods',
    'Supporting_Older_Browsers': 'Supporting Older Browsers',
    'Fundamental_Layout_Comprehension' : 'Fundamental Layout Comprehension',
    'Color_picker_tool': 'Color picker',
    'Box-shadow_generator': 'Box shadow generator',
    'Border-image_generator' : 'Border image generator',

    // TODO better place for that?
    'Animations': 'Animations',
    'Using CSS animations': 'Using CSS animations',
    'Backgrounds and Borders': 'Backgrounds and Borders',
    'Using multiple backgrounds': 'Using multiple backgrounds',
    'Resizing background images': 'Resizing background images',
    'Box model': 'Box model',
    'Box alignment': 'Box alignment',
    'Columns': 'Columns',
    'Conditional rules': 'Conditional rules',
    'CSSOM view': 'CSSOM view',
    'Flexbox': 'Flexbox',
    'Flow layout': 'Flow layout',
    'Fonts': 'Fonts',
    'Grid': 'Grid',
    'Images': 'Images',
    'Lists and counters': 'Lists and counters',
    'Logical properties': 'Logical properties',
    'Media queries': 'Media queries',
    'Positioning': 'Positioning',
    'Scroll snap': 'Scroll snap',
    'Shapes': 'Shapes',
    'Text': 'Text',
    'Transforms': 'Transforms',
    'Transitions': 'Transitions',
    'Layout cookbook': 'Layout cookbook',
    'Tools': 'Tools',
    "Box alignment in block layout": "Box alignment in block layout",
    "Box alignment in flexbox": "Box alignment in flexbox",
    "Box alignment in grid layout": "Box alignment in grid layout",
    "Box alignment in multi-column layout": "Box alignment in multi-column layout",
    "Introduction to the CSS basic box model": "Introduction to the CSS basic box model",
    "Mastering margin collapsing": "Mastering margin collapsing",
    "Basic concepts of Multicol": "Basic concepts of Multicol",
    "Styling columns": "Styling columns",
    "Spanning and balancing": "Spanning and balancing",
    "Handling overflow in Multicol": "Handling overflow in Multicol",
    "Content breaks in Multicol": "Content breaks in Multicol",
    "Using feature queries": "Using feature queries",
    "Coordinate systems": "Coordinate systems",
    "Basic concepts of Flexbox": "Basic concepts of Flexbox",
    "Comparison with other layout methods": "Comparison with other layout methods",
    "Aligning items in a flex container": "Aligning items in a flex container",
    "Ordering flex items": "Ordering flex items",
    "Controlling flex item ratios": "Controlling flex item ratios",
    "Mastering wrapping of flex items": "Mastering wrapping of flex items",
    "Typical use cases of Flexbox": "Typical use cases of Flexbox",
    "Backwards compatibility of Flexbox": "Backwards compatibility of Flexbox",
    "Block and Inline layout in normal flow": "Block and Inline layout in normal flow",
    "In flow and Out of flow": "In flow and Out of flow",
    "Formatting contexts explained": "Formatting contexts explained",
    "Flow layout and writing modes": "Flow layout and writing modes",
    "Flow layout and overflow": "Flow layout and overflow",
    "OpenType font features guide": "OpenType font features guide",
    "Variable fonts guide": "Variable fonts guide",
    "Basics concepts of grid layout": "Basics concepts of grid layout",
    "Relationship to other layout methods": "Relationship to other layout methods",
    "Line-based placement": "Line-based placement",
    "Grid template areas": "Grid template areas",
    "Layout using named grid lines": "Layout using named grid lines",
    "Auto-placement in grid layout": "Auto-placement in grid layout",
    "Box alignment in grid layout": "Box alignment in grid layout",
    "Grids, logical values and writing modes": "Grids, logical values and writing modes",
    "Grid layout and accessibility": "Grid layout and accessibility",
    "Grid Layout and progressive enhancement": "Grid Layout and progressive enhancement",
    "Realizing common layouts using grids": "Realizing common layouts using grids",
    "Subgrid": "Subgrid",
    "Masonry layout": "Masonry layout",
    "Using CSS gradients": "Using CSS gradients",
    "Using CSS counters": "Using CSS counters",
    "Consistent list indentation": "Consistent list indentation",
    "Basic concepts": "Basic concepts",
    "Floating and positioning": "Floating and positioning",
    "Margins, borders and padding": "Margins, borders and padding",
    "Sizing": "Sizing",
    "Using media queries": "Using media queries",
    "Using media queries for accessibility": "Using media queries for accessibility",
    "Testing media queries programmatically": "Testing media queries programmatically",
    "Understanding CSS z-index": "Understanding CSS z-index",
    "Basic concepts of scroll snap": "Basic concepts of scroll snap",
    "Browser compatibility and scroll snap": "Browser compatibility and scroll snap",
    "Overview of shapes": "Overview of shapes",
    "Shapes from box values": "Shapes from box values",
    "Basic shapes": "Basic shapes",
    "Shapes from images": "Shapes from images",
    "Wrapping and breaking text": "Wrapping and breaking text",
    "Using transforms": "Using transforms",
    "Using transitions": "Using transitions",
    "Media objects": "Media objects",
    "Columns": "Columns",
    "Center an element": "Center an element",
    "Sticky footers": "Sticky footers",
    "Split navigation": "Split navigation",
    "Breadcrumb navigation": "Breadcrumb navigation",
    "List group with badges": "List group with badges",
    "Pagination": "Pagination",
    "Card": "Card",
    "Grid wrapper": "Grid wrapper",
}

module.exports.navLabels = labels;
module.exports.default = () => '';