const labels = {
  JavaScript: 'JavaScript',
  Overview: 'JavaScript technologies overview',
  Tutorials: 'Tutorials:',
  Guide: 'JavaScript Guide',
  Guide_Introduction: 'Introduction',
  Guide_Grammar: 'Grammar and types',
  Guide_Control_flow: 'Control flow and error handling',
  Guide_Loops: 'Loops and iteration',
  Guide_Functions: 'Functions',
  Guide_Expressions: 'Expressions and operators',
  Guide_Numbers: 'Numbers and dates',
  Guide_Text: 'Text formatting',
  Guide_RegExp: 'Regular expressions',
  Guide_Indexed_collections: 'Indexed collections',
  Guide_keyed_collections: 'Keyed collections',
  Guide_Objects: 'Working with objects',
  Guide_OOP: 'Details of the object model',
  Guide_promises: 'Using promises',
  Guide_Iterators_Generators: 'Iterators and generators',
  Guide_Meta: 'Meta programming',
  Guide_Modules: 'JavaScript modules',
  Complete_beginners: 'Complete beginners',
  Basics: 'JavaScript basics',
  First_steps: 'JavaScript first steps',
  Building_blocks: 'JavaScript building blocks',
  Intermediate: 'Intermediate',
  Introducing_objects: 'Introducing JavaScript objects',
  'Client-side_APIs': 'Client-side web APIs',
  Frameworks: 'Client-side JavaScript frameworks',
  'Re-introduction': 'A re-introduction to JavaScript',
  Data_structures: 'JavaScript data structures',
  Equality: 'Equality comparisons and sameness',
  Closures: 'Closures',
  Advanced: 'Advanced',
  Inheritance: 'Inheritance and the prototype chain',
  Strict_mode: 'Strict mode',
  Typed_arrays: 'JavaScript typed arrays',
  Memory_Management: 'Memory Management',
  Event_Loop: 'Concurrency model and Event Loop',
  Reference: 'References:',
  Global_Objects: 'Built-in objects',
  Operators: 'Expressions & operators',
  Statements: 'Statements & declarations',
  Functions: 'Functions',
  Classes: 'Classes',
  Errors: 'Errors',
  More: 'Misc',
  Lexical_grammar: 'Lexical grammar',
  Enumerability: 'Enumerability and ownership of properties',
  Data_types: 'Data types and data structures',
  Iteration_protocols: 'Iteration protocols',
  Transitioning_to_strict_mode: 'Transitioning to strict mode',
  Template_strings: 'Template literals',
  Deprecated_features: 'Deprecated features',
};

const inheritanceData = {
  Math: ['Object'],
  Date: ['Object'],
  Function: ['Object'],
  Object: [],
  JSON: ['Object'],
  Intl: ['Object'],
  arguments: [],
  Reflect: ['Object'],
  Proxy: [],
  Atomics: ['Object'],
  WebAssembly: ['Object'],
  default: ['Object', 'Function'],
};

const groupData = {
  Error: [
    'Error',
    'EvalError',
    'InternalError',
    'RangeError',
    'ReferenceError',
    'SyntaxError',
    'TypeError',
    'URIError',
  ],
  Intl: [
    'Intl',
    'Collator',
    'DateTimeFormat',
    'ListFormat',
    'NumberFormat',
    'PluralRules',
    'RelativeTimeFormat',
  ],
  TypedArray: [
    'TypedArray',
    'Int8Array',
    'Uint8Array',
    'Uint8ClampedArray',
    'Int16Array',
    'Uint16Array',
    'Int32Array',
    'Uint32Array',
    'Float32Array',
    'Float64Array',
    'BigInt64Array',
    'BigUint64Array',
  ],
  Proxy: ['Proxy', 'handler'],
  WebAssembly: [
    'WebAssembly',
    'WebAssembly.Module',
    'WebAssembly.Global',
    'WebAssembly.Instance',
    'WebAssembly.Memory',
    'WebAssembly.Table',
    'WebAssembly.CompileError',
    'WebAssembly.LinkError',
    'WebAssembly.RuntimeError',
  ],
};

module.exports.navLabels = labels;
module.exports.inheritanceData = inheritanceData;
module.exports.groupData = groupData;
module.exports.default = () => '';
