const labels = {
  JavaScript: 'JavaScript',
  Overview: 'Огляд JavaScript-технологій',
  Tutorials: 'Посібники:',
  Guide: 'Настанови по JavaScript',
  Guide_Introduction: 'Вступ',
  Guide_Grammar: 'Граматика та типи',
  Guide_Control_flow: 'Керування потоком та обробка помилок',
  Guide_Loops: 'Цикли та перебори',
  Guide_Functions: 'Функції',
  Guide_Expressions: 'Вирази та оператори',
  Guide_Numbers: 'Числа та дати',
  Guide_Text: 'Форматування тексту',
  Guide_RegExp: 'Регулярні вирази',
  Guide_Indexed_collections: 'Колекції з індексами',
  Guide_keyed_collections: 'Колекції з ключами',
  Guide_Objects: "Робота щ об'єктами",
  Guide_OOP: "Докладно про об'єктну модель",
  Guide_promises: 'Застосування промісів',
  Guide_Iterators_Generators: 'Ітератори та генератори',
  Guide_Meta: 'Метапрограмування',
  Guide_Modules: 'Модулі JavaScript',
  Complete_beginners: 'Для цілковитих початківців',
  Basics: 'Основи JavaScript',
  First_steps: 'Перші кроки з JavaScript',
  Building_blocks: 'Конструктивні блоки JavaScript',
  Intermediate: 'Середній рівень',
  Introducing_objects: "Вступ до об'єктів у JavaScript",
  'Client-side_APIs': 'Клієнтські веб-API',
  Frameworks: 'Клієнтські фреймворки у JavaScript',
  'Re-introduction': 'Повторний вступ до JavaScript',
  Data_structures: 'Структури даних у JavaScript',
  Equality: 'Порівняння на схожість і однаковість',
  Closures: 'Замикання',
  Advanced: 'Поглиблене вивчення',
  Inheritance: 'Наслідування та ланцюжок прототипів',
  Strict_mode: 'Суворий режим',
  Typed_arrays: 'Типізовані масиви JavaScript',
  Memory_Management: "Керування пам'яттю",
  Event_Loop: 'Модель багатопотоковості та Цикл подій',
  Reference: 'Довідки:',
  Global_Objects: "Вбудовані об'єкти",
  Operators: 'Вирази та оператори',
  Statements: 'Інструкції та оголошення',
  Functions: 'Функції',
  Classes: 'Класи',
  Errors: 'Помилки',
  More: 'Різне',
  Lexical_grammar: 'Лексична граматика',
  Enumerability: 'Перелічуваність і належність властивостей',
  Data_types: 'Типи і структури даних',
  Iteration_protocols: 'Протоколи перебирання',
  Transitioning_to_strict_mode: 'Перехід до суворого режиму',
  Template_strings: 'Літерали шаблону',
  Deprecated_features: 'Застарілий функціонал',
};

const inheritanceData = {
  Math: ['Object'],
  Date: ['Object'],
  Function: ['Object'],
  Object: [],
  JSON: ['Object'],
  Intl: ['Object'],
  arguments: [],
  Reflect: ['Object'],
  Proxy: [],
  Atomics: ['Object'],
  WebAssembly: ['Object'],
  default: ['Object', 'Function'],
};

const groupData = {
  Error: [
    'Error',
    'EvalError',
    'InternalError',
    'RangeError',
    'ReferenceError',
    'SyntaxError',
    'TypeError',
    'URIError',
  ],
  Intl: [
    'Intl',
    'Collator',
    'DateTimeFormat',
    'ListFormat',
    'NumberFormat',
    'PluralRules',
    'RelativeTimeFormat',
  ],
  TypedArray: [
    'TypedArray',
    'Int8Array',
    'Uint8Array',
    'Uint8ClampedArray',
    'Int16Array',
    'Uint16Array',
    'Int32Array',
    'Uint32Array',
    'Float32Array',
    'Float64Array',
    'BigInt64Array',
    'BigUint64Array',
  ],
  Proxy: ['Proxy', 'handler'],
  WebAssembly: [
    'WebAssembly',
    'WebAssembly.Module',
    'WebAssembly.Global',
    'WebAssembly.Instance',
    'WebAssembly.Memory',
    'WebAssembly.Table',
    'WebAssembly.CompileError',
    'WebAssembly.LinkError',
    'WebAssembly.RuntimeError',
  ],
};

module.exports.navLabels = labels;
module.exports.inheritanceData = inheritanceData;
module.exports.groupData = groupData;
module.exports.default = () => '';
